name: AFKPatrol
main: xyz.olivermartin.afkpatrol.AFKPatrol
version: 1.1
api-version: 1.13
author: Oliver Martin (Revilo410)
commands:
   afkpatrol:
      description: Reload the plugin configuration
      usage: /afkpatrol reload
      permission: afkpatrol.reload
      permission-message: You do not have permission to reload the plugin
